# FIXED
source/DSP281x_DefaultIsr.obj: ../source/DSP281x_DefaultIsr.c
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Device.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_SysCtrl.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_DevEmu.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Xintf.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_CpuTimers.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_PieCtrl.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_PieVect.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Spi.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Sci.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Mcbsp.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_ECan.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Gpio.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Ev.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Adc.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_XIntrupt.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_Examples.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_GlobalPrototypes.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_SWPrioritizedIsrLevels.h
source/DSP281x_DefaultIsr.obj: C:/Users/ACIP-Lee/Documents/workspace/D-STATCOM_ByLee/include/DSP281x_DefaultISR.h
